import type { InfraRule } from '../types';

export const DOCKERFILE_RULES: InfraRule[] = [
  {
    id: 'INFRA-001',
    severity: 'high',
    fileType: 'dockerfile',
    title: 'Container running as root',
    description: 'No USER instruction found. The container will run as root, increasing the blast radius of any vulnerability.',
    remediation: 'Add a USER instruction to switch to a non-root user: USER node (or USER 1000).',
    pattern: /^\s*USER\s+\S+/im,
    negativeMatch: true,
  },
  {
    id: 'INFRA-002',
    severity: 'high',
    fileType: 'dockerfile',
    title: 'Using "latest" tag for base image',
    description: 'FROM instruction uses :latest or no tag. Builds are not reproducible and may break unexpectedly.',
    remediation: 'Pin the base image to a specific version: FROM node:20-alpine instead of FROM node:latest.',
    pattern: /^\s*FROM\s+\S+(?::latest\s*$|\s+(?!AS))/im,
  },
  {
    id: 'INFRA-003',
    severity: 'critical',
    fileType: 'dockerfile',
    title: 'Secrets in ENV/ARG instruction',
    description: 'Sensitive values (passwords, tokens, keys) are hardcoded in ENV or ARG. These are visible in image layers.',
    remediation: 'Use build-time secrets (--mount=type=secret) or runtime environment variables instead of ENV/ARG.',
    pattern: /^\s*(?:ENV|ARG)\s+\S*(?:PASSWORD|SECRET|TOKEN|API_KEY|PRIVATE_KEY)\s*=/im,
  },
  {
    id: 'INFRA-004',
    severity: 'medium',
    fileType: 'dockerfile',
    title: 'COPY of sensitive files',
    description: 'Dockerfile copies files that may contain secrets (.env, .pem, credentials).',
    remediation: 'Add sensitive files to .dockerignore. Use Docker secrets or mount for sensitive data.',
    pattern: /^\s*COPY\s+.*(?:\.env|\.pem|\.key|credentials|secrets)\b/im,
  },
  {
    id: 'INFRA-005',
    severity: 'medium',
    fileType: 'dockerfile',
    title: 'Exposed sensitive port',
    description: 'Exposes a port commonly used by databases or admin services (22, 3306, 5432, 6379, 27017).',
    remediation: 'Only expose application ports. Use Docker networking for internal service communication.',
    pattern: /^\s*EXPOSE\s+(?:22|3306|5432|6379|27017)\b/im,
  },
  {
    id: 'INFRA-006',
    severity: 'low',
    fileType: 'dockerfile',
    title: 'No HEALTHCHECK instruction',
    description: 'No HEALTHCHECK defined. Container orchestrators cannot determine if the application is healthy.',
    remediation: 'Add HEALTHCHECK CMD curl -f http://localhost:PORT/health || exit 1.',
    pattern: /^\s*HEALTHCHECK\s+/im,
    negativeMatch: true,
  },
  {
    id: 'INFRA-007',
    severity: 'medium',
    fileType: 'dockerfile',
    title: 'Using ADD instead of COPY',
    description: 'ADD can auto-extract archives and fetch URLs, which is unexpected. COPY is safer and more explicit.',
    remediation: 'Replace ADD with COPY unless you specifically need URL fetching or archive extraction.',
    pattern: /^\s*ADD\s+(?!--chown)/im,
  },
  {
    id: 'INFRA-008',
    severity: 'high',
    fileType: 'dockerfile',
    title: 'SSL verification disabled in RUN',
    description: 'RUN command disables SSL verification (--no-check-certificate, --insecure, SSL_VERIFY=false).',
    remediation: 'Fix the root cause (install CA certificates) instead of disabling SSL verification.',
    pattern: /^\s*RUN\s+.*(?:--no-check-certificate|--insecure|SSL_VERIFY\s*=\s*(?:false|0)|NODE_TLS_REJECT_UNAUTHORIZED\s*=\s*0)/im,
  },
  {
    id: 'INFRA-009',
    severity: 'medium',
    fileType: 'dockerfile',
    title: 'Using chmod 777',
    description: 'Setting world-writable permissions (chmod 777) is a security risk in containers.',
    remediation: 'Use the least permissive mode needed: chmod 755 for directories, chmod 644 for files.',
    pattern: /^\s*RUN\s+.*chmod\s+777\b/im,
  },
  {
    id: 'INFRA-010',
    severity: 'high',
    fileType: 'dockerfile',
    title: 'Hardcoded password in RUN command',
    description: 'RUN command contains what appears to be a hardcoded password or secret.',
    remediation: 'Use Docker build secrets (--mount=type=secret) or runtime environment variables.',
    pattern: /^\s*RUN\s+.*(?:--password\s+\S|MYSQL_ROOT_PASSWORD|POSTGRES_PASSWORD)\b/im,
  },
  {
    id: 'INFRA-011',
    severity: 'medium',
    fileType: 'dockerfile',
    title: 'Package install without version pinning',
    description: 'Installing packages without pinned versions makes builds non-reproducible.',
    remediation: 'Pin package versions: apt-get install package=version, pip install package==version.',
    pattern: /^\s*RUN\s+(?:apt-get\s+install|apk\s+add)\s+(?!.*=).*\S/im,
  },
];
