import type { InfraRule } from '../types';

export const GITHUB_ACTIONS_RULES: InfraRule[] = [
  {
    id: 'INFRA-020',
    severity: 'high',
    fileType: 'github-actions',
    title: 'Unpinned action version',
    description: 'Action uses @main, @master, or a mutable tag instead of a pinned SHA. Supply chain attacks can inject malicious code.',
    remediation: 'Pin actions to a full commit SHA: uses: actions/checkout@abcdef1234567890 instead of @v4.',
    pattern: /uses:\s+\S+@(?:main|master)\b/i,
  },
  {
    id: 'INFRA-021',
    severity: 'critical',
    fileType: 'github-actions',
    title: 'Secrets in plaintext',
    description: 'Workflow file contains what appears to be a hardcoded secret, token, or password.',
    remediation: 'Use GitHub Actions secrets: ${{ secrets.MY_SECRET }} instead of hardcoded values.',
    pattern: /(?:password|token|secret|api_key)\s*[:=]\s*['"][^${\s][^'"]+['"]/i,
  },
  {
    id: 'INFRA-022',
    severity: 'high',
    fileType: 'github-actions',
    title: 'pull_request_target with code checkout',
    description: 'Using pull_request_target with actions/checkout checks out the PR head, which can execute arbitrary code from forks.',
    remediation: 'Use pull_request event instead, or avoid checking out PR code in pull_request_target workflows.',
    pattern: /pull_request_target/i,
  },
  {
    id: 'INFRA-023',
    severity: 'medium',
    fileType: 'github-actions',
    title: 'Overly permissive permissions',
    description: 'Workflow grants write-all permissions, giving all steps full access to repo, packages, and deployments.',
    remediation: 'Use the principle of least privilege: specify only the permissions each job needs.',
    pattern: /permissions:\s*write-all/i,
  },
  {
    id: 'INFRA-024',
    severity: 'high',
    fileType: 'github-actions',
    title: 'Script injection via github context',
    description: 'Using ${{ github.event.* }} directly in a run: step allows attackers to inject arbitrary commands via PR titles, branch names, etc.',
    remediation: 'Assign github context to an environment variable first, then reference $ENV_VAR in the script.',
    pattern: /run:.*\$\{\{\s*github\.event\./i,
  },
  {
    id: 'INFRA-025',
    severity: 'medium',
    fileType: 'github-actions',
    title: 'Self-hosted runner with public trigger',
    description: 'Self-hosted runners can be targeted by malicious PRs from forks. They have access to the host machine.',
    remediation: 'Only use self-hosted runners for private repos or with strict PR approval requirements.',
    pattern: /runs-on:\s*self-hosted/i,
  },
  {
    id: 'INFRA-026',
    severity: 'low',
    fileType: 'github-actions',
    title: 'No timeout-minutes set',
    description: 'Jobs without timeout-minutes can run indefinitely, consuming runner resources and billing.',
    remediation: 'Add timeout-minutes to each job: timeout-minutes: 30.',
    pattern: /timeout-minutes:/i,
    negativeMatch: true,
  },
  {
    id: 'INFRA-027',
    severity: 'medium',
    fileType: 'github-actions',
    title: 'Persist credentials enabled on checkout',
    description: 'actions/checkout with persist-credentials: true leaves the token in .git/config, accessible to subsequent steps.',
    remediation: 'Set persist-credentials: false on actions/checkout when the token is not needed after checkout.',
    pattern: /persist-credentials:\s*true/i,
  },
  {
    id: 'INFRA-028',
    severity: 'high',
    fileType: 'github-actions',
    title: 'Uploading artifacts with sensitive patterns',
    description: 'Upload artifact step includes paths that may contain secrets (.env, credentials, keys).',
    remediation: 'Exclude sensitive files from artifact uploads. Use .gitignore-style patterns in the path.',
    pattern: /upload-artifact[\s\S]*?path:.*(?:\.env|credentials|\.key|\.pem|secrets)/i,
  },
  {
    id: 'INFRA-029',
    severity: 'medium',
    fileType: 'github-actions',
    title: 'Third-party action without version pinning',
    description: 'Using a third-party action with only a major version tag (@v1). The tag can be moved to point to different code.',
    remediation: 'Pin third-party actions to a full commit SHA for supply chain security.',
    pattern: /uses:\s+(?!actions\/)[^@\s]+@v\d+\s*$/im,
  },
];
